### ISSUE TITLE
Heuristics function

### ISSUE THREAD

**Issue by Jashani** [Jashani/Prolect#6]

**Comment by BenAvtabi** [comment]
I don't know how your heuristic stuff currently work, it seemed to be a cumulative score thing?
Anyway, you need to add an "override" functionality to that:
If X happens, it should override the score.

For example, when there's repetition, no matter what else happens, the score should be 0.
Same thing goes for stalemate (valid_moves returns an empty list).
I assume also mates need to override the score to something stupid (unless you trust "taking the king" to give enough score, and so "finding mates" is the same as looking a turn deeper and "taking the king".

**Comment by BenAvtabi** [comment]
Let's have different heuristic functions be used for different difficulties, with the most basic being used by all, and advanced ones only used by higher difficulties.
Perhaps we can make this distinction by adding a Difficulty parameter to each of them, and something like:
foo(_, easy, 0) :- !.
foo(Pieces, _, Score) :-
 %actual implementation here

and then when they are used and their score is added up, they won't contribute for easy difficulty for example.

For overring functions (see previous comment) we just need them to not be implemented at all for lower difficulties.
So for example:
foo(Pieces, hard, Score) :-
 %actual implementation here
 
or
foo(Pieces, Difficulty, Score) :-
Difficulty = medium ; Difficulty = hard,
 %actual implementation here
 
 or
 foo(Pieces, _, Score) :-
 Difficulty =\= easy
 %actual implementation here
 
 etc
